name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Git Identity
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: wildandw
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Prepare output branch
        run: |
          git fetch origin output || echo "output branch does not exist yet"
          git switch --orphan output
          rm -rf .
          mkdir -p dist
          cp ../dist/github-contribution-grid-snake.svg dist/
          touch .nojekyll
          git add .
          git commit -m "generate snake
